### ISSUE TITLE
Missing ARM64 Android architecture files

### ISSUE THREAD

**Issue by Alphadamos** [AdColony/AdColony-Unity-Plugin#10]
Currently, the AdColony unitypackage does not include lib files to support the ARM64 architecture. Your article mentions your awareness of the issue, but I am unable to locate the relevant files as the GooglePlay submission deadline creeps closer.

https://www.adcolony.com/blog/2019/02/04/mobile-monday-64-bits-for-android-apps-video-ad-spend-keeps-growing/

**Comment by Alphadamos** [comment]
We're using the work-around of replacing "/Plugins/Android/AdColony/libs/AdColony.jar" with the Android one (https://github.com/AdColony/AdColony-Android-SDK-3/blob/master/Library/adcolony.jar) and renaming it accordingly.

**Comment by akwkong** [comment]
We removed the native libraries in version 3.3.7 of our Android SDK:
https://github.com/AdColony/AdColony-Android-SDK-3/blob/master/CHANGELOG.md#337-20181206

Our Unity Plugin takes this into consideration and does not include the libadcolony.so or libjs.so files in the AdColony.unitypackage file anymore. From my understanding, if our plugin does not include any native libraries, including it in your app should require no modifications to support the ARM64 architecture. Please let me know if that is not the case and we can get the Unity Plugin to a state that meets Google's requirements.

**Comment by Alphadamos** [comment]
I apologize! The error was on our side. We completely removed all of the old files and updated to latest Unity Plugin version (3.3.10), and it's working as intended.

Thank you!
