### ISSUE TITLE
Live ads are not showing even test mode is off 

### ISSUE THREAD

**Issue by faizans3531** [AdColony/AdColony-Unity-Plugin#12]
hi sir my test ads are working fine and when a turn off the test mode my live ads are not showing on device my app is live but latest apk not uploaded with adcolony can i check my live ads during dev mode or the live after i i upload the latest apk on console

**Comment by alasdairpressney** [comment]
Hi @faizans3531 - If test ads are showing then your SDK integration is correct.

Live ads are subject to availability and this varies by region and app. Please contact our account management team for more information about ad availability: https://www.adcolony.com/publishers/

**Comment by faizans3531** [comment]
i tested in different region but live ads are not working there also
