### ISSUE TITLE
test ads are running but live ads are not working

### ISSUE THREAD

**Issue by faizans3531** [AdColony/AdColony-Unity-Plugin#13]
sir my test ads are working and live ads are not working i have tested on different regions but live ads are not working there also kindly guide where a i am making a mistake

**Comment by alasdairpressney** [comment]
Hi @faizans3531 - If test ads are showing then your SDK integration is correct and this is not a technical issue.

Please contact our account management team for more information about ad availability: https://www.adcolony.com/publishers/ or alternatively email New_business@adcolony.com
