### ISSUE TITLE
v.4.1.3.0 causes FileUsesReservedNameException while building AAB

### ISSUE THREAD

**Issue by VergilUa** [AdColony/AdColony-Unity-Plugin#16]
After upgrading gradle version of the AdColony to the 4.1.3.0 AAB build fails with the following exception:

11366: [Unity] FAILURE: Build failed with an exception.
11367: [Unity] * What went wrong:
11368: [Unity] Execution failed for task ':packageReleaseBundle'.
11369: [Unity] > java.util.concurrent.ExecutionException: com.android.tools.build.bundletool.exceptions.BundleFileTypesException$FileUsesReservedNameException: File 'root/AndroidManifest.xml' uses reserved file or directory name 'AndroidManifest.xml'.

This happens both locally and via Unity Cloud Build.
Although its being used as part of Applovin Max SDK mediation kit. 

IDK really is it AdColony or actually mediation adaptation of AppLovin that is crashing the build.

Workaround for that worked - using previous version of the plugin - 4.1.2.0;

APK builds just fine in both cases.

**Comment by MixMasterRickyC** [comment]
Had the same issue, looks like it's being tracked on the Android SDK github

https://github.com/AdColony/AdColony-Android-SDK/issues/72

**Comment by deamonik92** [comment]
Please checkout our latests release (4.6.0) of AdColony-Unity-Plugin if still having problems with AndroidManifest file.

In case this still occurs on latest version please contact us at support@adcolony.com.
