### ISSUE TITLE
Build fail Unity

### ISSUE THREAD

**Issue by janreng** [AdColony/AdColony-Unity-Plugin#18]
When I build aab and get the following error:

Execution failed for task ':packageReleaseBundle'.
> 1 exception was raised by workers:
com.android.tools.build.bundletool.exceptions.BundleFileTypesException$FileUsesReservedNameException: File 'root/AndroidManifest.xml' uses reserved file or directory name 'AndroidManifest.xml'.

How to fix?

**Comment by deamonik92** [comment]
Please checkout our latests release (4.6.0) of AdColony-Unity-Plugin if still having problems with AndroidManifest file. 

In case this still occurs on latest version please contact us at support@adcolony.com.
