### ISSUE TITLE
UIWebView - Deprecated API Usage

### ISSUE THREAD

**Issue by SteeBono** [AdColony/AdColony-Unity-Plugin#19]
Hi,

I uploaded a build of the game developed with Unity on the App Store Connect, and I received an email from Apple stating that there are still references to the UIWebView APIs.

<img width="678" alt="Schermata 2020-03-29 alle 20 06 11" src="https://user-images.githubusercontent.com/11635557/77856634-c2aa7300-71f8-11ea-8a8c-cfd07b904b27.png">

I checked the version I'm currently using of AdColony.
Below the information regarding the version:

AdColony Unity SDK Version: **4.1.2.0**
iOS SDK Version: **4.1.2**
Android SDK Version: **4.1.2**

I checked the AdColony SDK 4.1.2 (iOS) release notes and it says:
- **Updated OM SDK (no more UIWebView references)**

I have also tried with version 4.1.3 of the SDKs for Unity, but I have the same problem.

<img width="422" alt="Schermata 2020-03-29 alle 20 01 59" src="https://user-images.githubusercontent.com/11635557/77856614-a3abe100-71f8-11ea-9b11-e99471fbab74.png">

Could you check if there are still references?
I ask you, because this is the only external library that I use in my game and by performing an advanced search throughout the project, the only reference to the UIWebView is found in the binary file 'AdColony'.

<img width="703" alt="Schermata 2020-03-29 alle 20 15 33" src="https://user-images.githubusercontent.com/11635557/77856881-7ceeaa00-71fa-11ea-988c-fa75c8eb71c9.png">

Thank you,
Stefano

**Comment by lupatus** [comment]
iOS SDK v4.1.2 is free from UIWebView symbols, OM SDK v1.3.0 reintroduced the symbol (iOS SDK v4.1.3) and that was fixed with OM SDK v1.3.1 release which is integrated with iOS SDK v4.1.4.
So best update to latest version of SDK.

Regex will find few occurrences, but that's not symbol itself, use `nm` to search for symbols:

     # nm AdColony.framework/AdColony | grep UIWebView                                                                                                                     
    AdColony.framework/AdColony(OMIDUIWebViewJSExecutor.o):
    ---------------- t -[OMIDAdcolonyUIWebViewJSExecutor .cxx_destruct]
    ---------------- t -[OMIDAdcolonyUIWebViewJSExecutor initWithWebView:]
    ---------------- t -[OMIDAdcolonyUIWebViewJSExecutor injectJavaScriptFromString:]
    ---------------- t -[OMIDAdcolonyUIWebViewJSExecutor jsEnvironment]
    ---------------- t -[OMIDAdcolonyUIWebViewJSExecutor supportBackgroundThread]
    ---------------- D _OBJC_CLASS_$_OMIDAdcolonyUIWebViewJSExecutor
    ---------------- D _OBJC_IVAR_$_OMIDAdcolonyUIWebViewJSExecutor._webView
    ---------------- D _OBJC_METACLASS_$_OMIDAdcolonyUIWebViewJSExecutor
                     U _OBJC_CLASS_$_OMIDAdcolonyUIWebViewJSExecutor
