### ISSUE TITLE
AdColony build failed in android

### ISSUE THREAD

**Issue by umeshiscreative** [AdColony/AdColony-Unity-Plugin#21]
Hi,
I used the latest release 4.1.3 for ads, I used as per documentation but when I am trying to build the android project (not apk). Its failed with 
```
/Temp/StagingArea/android-libraries/AdColony' is missing AndroidManifest.xml file.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```
I want to know which files I need to manual copy or need to add postprocessor script for android?

**Comment by crmancera** [comment]
Hi @umeshiscreative! Could you solve this problem? i have the sale issue, thank you very much

**Comment by erihk2** [comment]
Hi @umeshiscreative! Could you solve this problem? i have the sale issue, thank you very much
