### ISSUE TITLE
adcolony plugin with unity 2020.1.3f1

### ISSUE THREAD

**Issue by odejinmi** [AdColony/AdColony-Unity-Plugin#27]
Whenever I add adcolony to my unity projects this is the error I got. can someone please help me?
ArgumentException: Requested value 'X86' was not found.
System.Enum+EnumResult.SetFailure (System.Enum+ParseFailureKind failure, System.String failureMessageID, System.Object failureMessageFormatArgument) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Enum.TryParseEnum (System.Type enumType, System.String value, System.Boolean ignoreCase, System.Enum+EnumResult& parseResult) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Enum.Parse (System.Type enumType, System.String value, System.Boolean ignoreCase) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Enum.Parse (System.Type enumType, System.String value) (at <fb001e01371b4adca20013e0ac763896>:0)
GooglePlayServices.AndroidAbis.EnumValueStringToInt (System.Type enumType, System.String enumValueString) (at <6804ee413fd14b908a616b3fd8ae92db>:0)
GooglePlayServices.AndroidAbis.get_Current () (at <6804ee413fd14b908a616b3fd8ae92db>:0)
GooglePlayServices.PlayServicesResolver.PollAndroidAbis () (at <6804ee413fd14b908a616b3fd8ae92db>:0)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <701f6580abad44cfb237a543dcd0d94b>:0)

**Comment by pchinn** [comment]
Hi @odejinmi , Please send an email to support@adcolony.com. Our Support team will assist you directly. Thanks.

**Comment by Hovhannisyan-K** [comment]
having the same problem, any news about this error?

**Comment by pchinn** [comment]
Hi @Hovhannisyan-K, Please send an email to support@adcolony.com. Our Support team will assist you directly. Thanks.

**Comment by odejinmi** [comment]
@pchinn not yet, please if you get any solution let me know

**Comment by odejinmi** [comment]
@pchinn not yet, please if you get any solution let me know

**Comment by pchinn** [comment]
Hi @odejinmi, Please send an email to support@adcolony.com. Our Support team will assist you directly. Thanks.

**Comment by reza-azimifar** [comment]
Having the same problem,  please help me? 👎 
ArgumentException: Requested value 'X86' was not found.
System.Enum+EnumResult.SetFailure (System.Enum+ParseFailureKind failure, System.String failureMessageID, System.Object failureMessageFormatArgument) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Enum.TryParseEnum (System.Type enumType, System.String value, System.Boolean ignoreCase, System.Enum+EnumResult& parseResult) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Enum.Parse (System.Type enumType, System.String value, System.Boolean ignoreCase) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Enum.Parse (System.Type enumType, System.String value) (at <fb001e01371b4adca20013e0ac763896>:0)
GooglePlayServices.AndroidAbis.EnumValueStringToInt (System.Type enumType, System.String enumValueString) (at <6804ee413fd14b908a616b3fd8ae92db>:0)
GooglePlayServices.AndroidAbis.get_Current () (at <6804ee413fd14b908a616b3fd8ae92db>:0)
GooglePlayServices.PlayServicesResolver.PollAndroidAbis () (at <6804ee413fd14b908a616b3fd8ae92db>:0)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <b17f35b08b864a3ca09a7032b437596e>:0)

**Comment by pchinn** [comment]
@reza-azimifar  - If you do a Google search, others have faced this issue from Unity:
1)  https://forum.unity.com/threads/argumentexception-requested-value-x86-was-not-found.684685/
2)  https://stackoverflow.com/questions/56309148/argumentexception-requested-value-x86-was-not-found
3) https://answers.unity.com/questions/1635061/argumentexception-requested-value-x86-was-not-foun.html

**Comment by deamonik92** [comment]
This issue has now been resolved with release of new version (4.6.0) of AdColony-Unity-Plugin
