### ISSUE TITLE
Unable to create ad within _OnAdColonyAdViewLoaded

### ISSUE THREAD

**Issue by mandelmonkey** [AdColony/AdColony-Unity-Plugin#29]
When setting dev ads on everything works as expected, however when turning them off to test real ads, ads do not load and I get ```Unable to create ad within _OnAdColonyAdViewLoaded```

is this expected behaviour? i.e. does it mean an ad wasnt available?

**Comment by pchinn** [comment]
Hi @mandelmonkey,  Please send an email to support@adcolony.com and our Support team will assist you directly.  Thank you.

**Comment by kshank2** [comment]
``https://clients.adcolony.com/zones/1416342

**Comment by kshank2** [comment]
#27

**Comment by kshank2** [comment]
https://github.com/AdColony/AdColony-Unity-Plugin/issues/29#issue-735629163
