### ISSUE TITLE
AdColony (3.3.8) not working on Amazon

### ISSUE THREAD

**Issue by MixMasterRickyC** [AdColony/AdColony-Unity-Plugin#5]
I've been having issues getting AdColony SDK (3.3.8) to work on Amazon devices since updating to the latest version. I'm seeing the below logcat error and OnConfigurationCompleted is never fired.

```
E/AdColony [ERROR]( 8295): Incomplete or disabled launch server response. Disabling AdColony until next launch.
```

There is no additional information in the logs and searching for this error hasn't returned anything.

We're also seeing the error below when launching the app but since GooglePlayServices isn't available on Amazon this isn't necessarily a problem.

```
W/System.err( 8295): com.google.android.gms.common.GooglePlayServicesNotAvailableException
W/System.err( 8295): 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source)
W/System.err( 8295): 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source)
W/System.err( 8295): 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source)
W/System.err( 8295): 	at com.adcolony.sdk.l.a(SourceFile:657)
W/System.err( 8295): 	at com.adcolony.sdk.a$1.run(SourceFile:44)
W/System.err( 8295): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 8295): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 8295): 	at java.lang.Thread.run(Thread.java:818)
```

This is the first time we've had an issue getting it to run, we've also seen an older version which had passed our QA also showing the same error response, that was running version (3.3.7)

Note: On Android, AdColony works fine and I see the OnConfigurationCompleted callback firing and adverts are displayed.

Any help with issue would be much appreciated,
Thanks.

**Comment by akwkong** [comment]
Could you please let us know the Fire OS version of your Amazon device? We noticed a crash that was happening only on Android Lollipop devices so we stopped serving ads to those devices. Fire OS 5 devices are based on Android 5.1.1.

We have an Android SDK release we are planning to release this week that should fix the crash. I will update this issue when that is available.

Like you mentioned, the GooglePlayServicesNotAvailableException is expected and it is handled by our SDK on Amazon devices.

**Comment by MixMasterRickyC** [comment]
Sure, the device the above logs are from is running Fire OS 5.3.6.4, but I can get you a further list of devices if that helps?

**Comment by akwkong** [comment]
Thanks for sharing your device info. Should be fine without the further list of devices. We just released the 3.3.9 Android SDK and Unity Plugin. Could you give that a try and see if it works for you now?

**Comment by MixMasterRickyC** [comment]
Thanks, just updated to 3.3.9 and it looks to be working again.

One thing I did notice whilst it was in a broken state, when requesting an interstitial advert, the OnRequestInterstitialFailedWithZone was never fired which I'd kind of expect it would do.

**Comment by akwkong** [comment]
Glad it is working for you after updating to 3.3.9!

Ah, that is interesting. I tried myself and was able to get the OnRequestInterstitialFailedWithZone callback fired in the broken state. Could you check if OnRequestInterstitialFailedWithZone is getting fired now that you are getting ads? You can force it to fire by calling AdColony.Ads.RequestInterstitialAd with an invalid zone ID after calling AdColony.Ads.Configure.
