### ISSUE TITLE
ADCDependencies null reference when using google play resolver 1.2.110.0

### ISSUE THREAD

**Issue by MixMasterRickyC** [AdColony/AdColony-Unity-Plugin#9]
I'm in the middle of updating to the latest MoPub SDK (5.7.1) from (5.6.0) . With the new version of MoPub SDK comes a new version of the PlayServicesResolver (1.2.110.0) from (v1.2.102.0)

This doesn't seem to play nice with the ADCDependencies which throws a NullReferenceException, see below.

```
svcSupport = svcSupport ?? Google.VersionHandler.InvokeStaticMethod(
              playServicesSupport, "CreateInstance",
              new object[] {
                  "GooglePlayGames",
                  EditorPrefs.GetString("AndroidSdkRoot"),
                  "ProjectSettings"
              });
```
throws 
```
NullReferenceException: Object reference not set to an instance of an object
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for ADCDependencies
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
```

I'm on the latest version of the ADColony SDK (3.3.9) 

Are there plans for a new version of the ADColony SDK for Unity? Any short time changes I can do to fix this issue?

**Comment by deamonik92** [comment]
Please checkout our latest release (4.6.0) of AdColony-Unity-Plugin if still having problems with ADCDependencies.

In case this still occurs on latest version please contact us at support@adcolony.com.
